# Generated by Django 5.1.3 on 2024-11-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('repeatpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='loginModel',
        ),
    ]
