# Generated by Django 5.1.3 on 2024-12-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocationMarkerss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsHuis', models.DecimalField(decimal_places=3, max_digits=3)),
                ('isKantoor', models.DecimalField(decimal_places=3, max_digits=3)),
                ('IsRave', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
