# Generated by Django 5.1.3 on 2024-12-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_maplocationmarkerss_markerlatitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapLocationMarkerss',
        ),
    ]
