# Generated by Django 5.1.3 on 2024-12-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0003_delete_maplocationmarkerss'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocationMarkerss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsHuis', models.FloatField()),
                ('isKantoor', models.FloatField()),
                ('IsRave', models.FloatField()),
                ('MarkerLatitude', models.FloatField()),
                ('MarkerLongtitude', models.FloatField()),
            ],
        ),
    ]
