# Generated by Django 5.1.3 on 2024-12-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapLocationMarkerss',
            new_name='MapLocationMarkers',
        ),
    ]
