# Generated by Django 5.1.3 on 2024-12-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_maplocationmarkerss_maplocationmarkers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplocationmarkers',
            old_name='isKantoor',
            new_name='IsKantoor',
        ),
    ]
